### ISSUE TITLE
plot.time_series in timeSeries.R: Extending functionality for plotting

### ISSUE THREAD

**Issue by tscoleman** [lindbrook/cholera#1]
I have a suggestion for slightly extending the functionality of plot.time_series, to allow passing of more arguments: "type", "lwd", "frame.plot", and "main". The reason is wanting to plot the time-series closer to the graphics of Tufte - something like the attached

[SnowBroadTimeSeries.pdf](https://github.com/lindbrook/cholera/files/2236523/SnowBroadTimeSeries.pdf)

Would you be amenable to my sending you the changed code (so you can review) or my initiating a pull request?

Thomas

**Comment by lindbrook** [comment]
Thanks for your suggestions!

I’ll probably formally open the repository to pull requests with version >= 0.6.0. For now, I’d appreciate it if you’d email me your code. It’d helpful to see how you approached the problem.

**Comment by tscoleman** [comment]
Here’s the code, plus the command I used to produce the .pdf


plot(timeSeries(),type="h",frame.plot=FALSE,pump.handle=FALSE,
	main="Deaths from Cholera, each day in 1854",lwd=2,statistic = "deaths",
	cex.main=1.75, cex.axis=1.75, cex.lab=1.75)





___________________
Thomas Coleman
203-252-4897 (mobile)
Risk books: http://closemountain.com/risk-management-books/ <http://closemountain.com/risk-management-books/>

**Comment by lindbrook** [comment]
Your code should now work. You should be able pass most if not all the graphical arguments. Two caveats:

1) You'll need to install 'cholera' version 0.5.0.9005, which is on GitHub. You may need to install the 'devtools' package: 

install.packages("devtools")

And then: 

devtools::install_github("lindbrook/cholera", build_vignettes = TRUE)

The changes will be on CRAN in version 0.5.1, but that won't be posted till mid-August.

2) To get rid of the box around the plot, use bty = "n" (box type) instead of frame.plot = FALSE:

plot(timeSeries(), type = "h", bty = "n", pump.handle = FALSE, 
  main = "Death from Cholera, each day in 1854", lwd = 2, statistic = "deaths", 
  cex.main = 1.75, cex.axis = 1.75, cex.lab = 1.75)

**Comment by tscoleman** [comment]
Peter,

If you are interested, I have posted on SSRN a paper about Snow that uses (and I hope properly credits) your application

“Causality in the Time of Cholera: John Snow as a Prototype for Causal Inference”

https://ssrn.com/abstract=3262234 <https://ssrn.com/abstract=3262234>




______________________
Thomas Coleman
Lecturer 
University of Chicago Harris School of Public Policy
203-252-4897 (mobile)
Risk books: http://closemountain.com/risk-management-books/ <http://closemountain.com/risk-management-books/>

**Comment by lindbrook** [comment]
For what it's worth, there's an R function for that: citation("pkg")
